# Generated by Django 3.2.2 on 2021-05-08 04:41

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(default=device.models.Device.key_default, editable=False, max_length=255),
        ),
    ]
